[tools]
node = "lts"
ruby = "latest"
deno = "latest"
flutter = "3.41.6"
usage = "latest"
dart = "latest"
"pipx:argcomplete" = "latest"
"pipx:black" = "latest"
"pipx:commitizen" = "latest"
"pipx:platformio" = "latest"
"pipx:poetry" = "latest"
python = "3.11.10"
uv = "latest"
bun = "latest"
pnpm = "latest"
"npm:@vercel/next-browser" = "latest"
"npm:agent-browser" = "latest"
fnox = "latest"

[settings]
experimental = true
disable_hints = ["false"]
python.uv_venv_auto = true
python.github_attestations = false
idiomatic_version_file_enable_tools = []
